### ISSUE TITLE
Request - Preview ship graphic in ES

### ISSUE THREAD

**Issue by davidwhitman** [evan153/Endless-Sky-Ship-Generator#1]
tldr: Request to be able to upload/link a ship sprite and have it displayed over an ES screenshot for easy previewing. 

So I saw yet another new ship mod just now, and it has some nice-looking artwork, but I've no idea how it would actually look ingame, with other ships around it. That gave me the idea to have a tool where you would basically just overlay some given sprite over a static ES screenshot (or a few), in order to more easily get a feel for what a ship *really* looks like, flying around. 

I think it would fit into your ship builder tool. Perhaps not.

**Comment by evan153** [comment]
I've wondered what some ships would look like in my mod before... I think it's a good idea, thanks.
